services:
  - type: web
    name: ecommerce-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn wsgi:app --bind=0.0.0.0:$PORT
